version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: gestion_deportiva
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/gestion_deportiva.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
